---

version: '3.8'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - appnya
      - pgadmin
    ports:
      - "80:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  appnya:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: appnya
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped
  
  spv:
    build:
      context: ./
      dockerfile: ./docker/spv/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: spv
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    links:
      - postgres
      - redis
    networks:
      - appnet

  # schedule:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/schedule/Dockerfile
  #     args:
  #       IMAGE_REGISTRY: ${IMAGE_REGISTRY}
  #       IMAGE_TAG: ${IMAGE_TAG}
  #   container_name: schedule
  #   volumes:
  #     - ${APP_PATH}/storage:/var/www/html/storage
  #   links:
  #     - postgres
  #     - redis
  #   networks:
  #     - appnet

  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped
  
  pgadmin:
    build:
      context: ./
      dockerfile: ./docker/pgadmin4/Dockerfile
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - appnet
  
  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    name: appnet
    driver: "bridge"

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  redis:
    driver: local