---

version: '3.8'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - appnya
    ports:
      - "80:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  appnya:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: appnya
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  # database:
  #   image: mysql:latest
  #   container_name: database
  #   restart: always
  #   volumes:
  #     - nginx_db_data:/var/lib/mysql
  #   ports:
  #     - "${DB_PORT}:3306"
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  #   networks:
  #     - appnet

networks:
  appnet:
    name: appnet
    driver: "bridge"
