---

version: '3.8'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - appnya1
      - appnya2
      - appnya3
      - appnya4
      - appnya5
      - appnya6
      - appnya7
      - appnya8
      - appnya9
      - appnya10
    ports:
      - "80:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  appnya1:
    build:
      context: ./
      dockerfile: ./docker/php/app1/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya1
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped
  
  appnya2:
    build:
      context: ./
      dockerfile: ./docker/php/app2/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya2
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya3:
    build:
      context: ./
      dockerfile: ./docker/php/app3/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya3
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped
  
  appnya4:
    build:
      context: ./
      dockerfile: ./docker/php/app4/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya4
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya5:
    build:
      context: ./
      dockerfile: ./docker/php/app5/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya5
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya6:
    build:
      context: ./
      dockerfile: ./docker/php/app6/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya6
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped
  
  appnya7:
    build:
      context: ./
      dockerfile: ./docker/php/app7/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya7
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya8:
    build:
      context: ./
      dockerfile: ./docker/php/app8/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya8
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya9:
    build:
      context: ./
      dockerfile: ./docker/php/app9/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya9
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  appnya10:
    build:
      context: ./
      dockerfile: ./docker/php/app10/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: appnya10
    links:
      - postgres 
      - redis
    depends_on:
      - redis
    volumes:
      - ${APP_PATH}/storage:/var/www/html/storage
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    restart: unless-stopped

  spv:
    build:
      context: ./
      dockerfile: ./docker/spv/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    container_name: spv
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    links:
      - postgres
      - redis
    networks:
      - appnet

  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped
  
  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    name: appnet
    driver: "bridge"

volumes:
  postgres:
    driver: local
  redis:
    driver: local